# Site settings
title: Wesley Rodrigues da Silva
subtitle: My personal website
email: wesley.it@gmail.com
description: This is my personal website.
baseurl: ""
url: "http://www.wesleyrodrigues.com.br"

twitter_username: wesleyit
github_username:  wesleyit
linkedin_username:  wesleyit
