# Site settings
title: Wesley Rodrigues
subtitle: Pesquisador, Arquiteto de Soluções de Cloud e Segurança
email: wesley.it@gmail.com
description: Wesley Rodrigues | Pesquisador, Arquiteto de Soluções de Cloud e Segurança
baseurl: ""
url: "http://www.wesleyrodrigues.com.br"

twitter_username: wesleyit
github_username:  wesleyit
linkedin_username:  wesleyit
